jwt:
  secret: JWT&AWP&SpringBoot&GeekBrains&Tim&Secret&String%#$%
  lifetime: 3600000


spring:
  security:

  profiles:
    active: work
    dev: dev
    work: work
  jta:
    atomikos:
      properties:
        default-max-wait-time-on-shutdown: