#The correct autorisation "token":**********
POST http://localhost:8080/api/v1/auth
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
#"message": "Incorrect username or password"
POST http://localhost:8080/api/v1/auth
Content-Type: application/json

{
  "username": "admin1",
  "password": "admin"
}

###
//
GET http://localhost:8080/api/v1/users/all

###
GET http://localhost:8080/api/v1/clients/all

###
GET http://localhost:8080/api/v1/credit_requests/all

###
GET http://localhost:8080/api/v1/credit_responses/all

###
GET http://localhost:8080/api/v1/credit_responses/1

###
GET http://localhost:8080/api/v1/contracts/1

###
GET http://localhost:8080/api/v1/contracts/all

###
GET http://localhost:8080/api/v1/clients/1


