POST http://localhost:8080/api/v1/credit_requests/
Content-Type: application/json

{
  "clientId": "1",
  "sum": "50000",
  "period": "24"
}

###

GET http://localhost:8080/api/v1/users/55
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNjU0MTY5MzM2LCJpYXQiOjE2NTQxNjU3MzZ9.kGOqcbKX7uUnjXxPQs6NdBSSqntAyP80jnpj6a79Nm0

###
GET http://localhost:8080/api/v1/credit_requests/1

###
GET http://localhost:8080/api/v1/credit_responses

###
GET http://localhost:8080/api/v1/credit_requests

###
GET http://localhost:8080/api/v1/credit_responses/all

###

GET http://localhost:8080/api/v1/contracts

###

GET http://localhost:8080/api/v1/clients/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNjUzNTgyNTMwLCJpYXQiOjE2NTM1Nzg5MzB9._d2Buucqqf-qsCtYKDe-S09Tu_9m9zLJ2hsETpc35qI

###

DELETE http://localhost:8080/api/v1/clients/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNjUzNTgyNTMwLCJpYXQiOjE2NTM1Nzg5MzB9._d2Buucqqf-qsCtYKDe-S09Tu_9m9zLJ2hsETpc35qI

###

DELETE http://localhost:8080/api/v1/credit_requests/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNjUzNTgyNTMwLCJpYXQiOjE2NTM1Nzg5MzB9._d2Buucqqf-qsCtYKDe-S09Tu_9m9zLJ2hsETpc35qI

###


GET http://localhost:8080/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNjUzNDk0ODQ5LCJpYXQiOjE2NTM0OTEyNDl9.veFTWmg2lQYlGSJucDJEvortcTZDRLMXEu_bP5jBUaE

###

GET http://localhost:8080/api/v1/users
#Authorization: Bearer {{auth_token}}
###


#The This username is occupied":**********
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###


#The correct autorisation "token":**********
POST http://localhost:8080/api/v1/auth
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
#The manager correct autorisation "token":**********
POST http://localhost:8080/api/v1/auth
Content-Type: application/json

{
  "username": "manager",
  "password": "1234"
}

###
#"message": "Incorrect username or password"
POST http://localhost:8080/api/v1/auth
Content-Type: application/json

{
  "username": "admin1",
  "password": "1234"
}
###


GET http://localhost:8080/api/v1/credit_responses/1

###
GET http://localhost:8080/api/v1/contracts/1

###
GET http://localhost:8080/api/v1/contracts/all

###
GET http://localhost:8080/api/v1/clients/1


