jwt:
  secret: JWT&AWP&SpringBoot&GeekBrains&Tim&Secret&String%#$%
  lifetime: 3600000


spring:
  security:

  jta:
    atomikos:
      properties:
        default-max-wait-time-on-shutdown:

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  profiles:
    active: dev
    dev: dev
    work: work
    dock: dock